### ISSUE TITLE
Suggestion: Require POE Window focus

### ISSUE THREAD

**Issue by MWLVegas** [totalschaden/copilot#13]
Unsure if this is something that can actually be done or not, or if it's already been addressed somewhere - but requiring window focus for POE would be grand, as right now if you happen to be on another window, Copilot will start spamming random letters trying to use skills.

**Comment by philpsk** [comment]
Excuse me i want to talk with u 
Plz Pm me: Discord :Hun#8907

**Comment by totalschaden** [comment]
Added
