### ISSUE TITLE
Getting error trying to use Steelskin.

### ISSUE THREAD

**Issue by TheRealZeagan** [totalschaden/copilot#2]
[Error](https://gyazo.com/dc4e60ce00ffb36149d5cb31dca33b33)

**Comment by Angrimoz** [comment]
Seems like the error is related to the new actorskills, got pretty much the same issue

[URL=https://www.casimages.com/i/200623010004685359.png.html][IMG]https://nsa40.casimages.com/img/2020/06/23/200623010004685359.png[/IMG][/URL]

**Comment by totalschaden** [comment]
Looks like you are missing the Actor Skills offsets that were pushed yesterday to Hud.

**Comment by Angrimoz** [comment]
True, Queuete changed the file and it's working now. Thanks
