### ISSUE TITLE
AutoQuit is enabled even if the checkbox is blank

### ISSUE THREAD

**Issue by rushtothesun** [totalschaden/CoPilot#2]
Loader is ran as admin, Plugin is loaded, AutoQuit checkbox is not Enabled, but when I press the hotkey I still disconnect. Changing the hotkey still has the same problem.

**Comment by totalschaden** [comment]
Hey, this is intended. The checkbox will only turn on/off the automated Quit. The Hotkey is intended as an "Oh Shit" option to quit fast even when the auto quit is off.
