### ISSUE TITLE
After latest update, custom skill doesn't work.

### ISSUE THREAD

**Issue by delolione** [totalschaden/copilot#21]
The custom skill trigger no longer works. I restarted the game and api even. Just wont trigger no matter what settings i change.

**Comment by totalschaden** [comment]
There seems to be a Problem with MonsterCheck, I will have a look.

**Comment by totalschaden** [comment]
Fixed the Issue, will push a fix along with other changes soon.

**Comment by totalschaden** [comment]
Pushed changes, let me know if it works for you now.

**Comment by delolione** [comment]
Works now. Thank you very much!
