### ISSUE TITLE
General's Cry 1 enemy check

### ISSUE THREAD

**Issue by Refnig** [totalschaden/copilot#22]
Hello. 

When there is only 1 enemy around in some cases warcry stops working. Looks like it works with white mobs, but don't with rare\unique around.

Is there a way to disable check for the enemy?

**Comment by totalschaden** [comment]
Hey, not playing atm so I wont look into this. Maybe next League incase i play that.

But here is something you can check, as all MonsterChecks are the same, and they used to work just fine:

If you want to Trigger it for ANY Mob, you have to set:

**Any 1
Rare 0
Unique 0**

**Comment by Ginfer** [comment]
There is no check for rarity, only for the range.
https://i.imgur.com/SjMaorP.png

**Comment by totalschaden** [comment]
Pushed Possible Fix

**Comment by Refnig** [comment]
Yep, it's working perfectly fine right now. Thank you.

**Comment by totalschaden** [comment]
Ok thanks for feedback, enjoy.
