### ISSUE TITLE
blade vortex doesnt work and plague bearer stops working

### ISSUE THREAD

**Issue by stussi** [totalschaden/copilot#24]
Hi :) plague bearer stops working if im activating BV too
and BV in gerneral dont work for me. redownloaded/readded the hud and the plugin. But BV is still not casting

would it be possible for you to take a look at it please? :)

**Comment by totalschaden** [comment]
Not currently playing, but Installed game and it looked fine.

Added Auto Seals while i was looking at it and some debug. (Also short tested and works fine)

**Comment by totalschaden** [comment]
As there is no further feedback and it works fine here ill close this.
