### ISSUE TITLE
Enduring cry <= rather than <

### ISSUE THREAD

**Issue by ThisIsFineCopium** [totalschaden/copilot#25]
Personally use enduring cry for endurance change generation rather than the regen, so would prefer if it just constantly tried to use it rather than if i'm below a hp threshold

So

#region Enduring Cry

                    if (Settings.enduringCryEnabled)
                        try
                        {
                            if (skill.Id == SkillInfo.enduringCry.Id)
                                if (SkillInfo.ManageCooldown(SkillInfo.enduringCry, skill))
                                    if (MonsterCheck(Settings.enduringCryTriggerRange, Settings.enduringCryMinAny,
                                            Settings.enduringCryMinRare, Settings.enduringCryMinUnique) && 
                                        (player.HPPercentage <= (float) Settings.enduringCryHealHpp / 100 ||
                                        player.ESPercentage <= (float) Settings.enduringCryHealEsp / 100)
                                        || Settings.enduringCrySpam)
                                        Keyboard.KeyPress(GetSkillInputKey(skill.SkillSlotIndex));
                        }
                        catch (Exception e)
                        {
                            LogError(e.ToString());
                        }

**Comment by ThisIsFineCopium** [comment]
if you'd like to change it / so i don't forget to change it myself in the future for personal use :)

**Comment by totalschaden** [comment]
Im not sure I understand the Issue, you could just Check Spam ? Or Use CTRL + Leftclick to set 101 %
