### ISSUE TITLE
[Feature Request] AutoQuit for Animate Guardian

### ISSUE THREAD

**Issue by mpalermo1983** [totalschaden/copilot#3]
I'd like to request if possible to add an auto-quit feature (pretty much similar to the existing one in the plugin) that monitors the player's Animate Guardian's health, this could be a lifesaver for lot of AGs out there equipped with 3ex+ items that may suddenly (and very quickly) go poof. Currently, it's very difficult to check on the AG's health (upper-left corner of the screen) while actually playing the game.

The implementation doesn't even need to be exactly like the player's auto-quit (with health slider and such), I'd be perfectly happy with a hardcoded autoquit when AG is < 50% health.

I'll be trying to see if I can perform the changes on my side on a local branch, it may take me a good while since I have poor programming experience (I could use some help, particularly with pointers and such), but if anybody could take this I'd be forever grateful.

Thanks for the hard work put in this.

**Comment by totalschaden** [comment]
Just pushed

**Comment by mpalermo1983** [comment]
Thank you very much totalschaden! I'll be testing this out today
