### ISSUE TITLE
[Feature Request] Just keep rage up using Enduring Cry

### ISSUE THREAD

**Issue by Murdoc84** [totalschaden/copilot#5]
Now it work like that:
If i have checked only: Keep Rage Up
![image](https://user-images.githubusercontent.com/22428605/89295369-2b9b6f00-d661-11ea-8b1e-0add2c7aadba.png)
It does not work

but if i check: Enduring Cry Enabled
![image](https://user-images.githubusercontent.com/22428605/89295460-5259a580-d661-11ea-9ac7-6167f243b1ce.png)
it push skill when monster in range

I want to use it in this way:
Use skill to get all Rage stacks (in my situation 10), next use skill only when rage timer is near to end (eg 2sec before).

Is it possible?

**Comment by totalschaden** [comment]
Not sure what the Issue would be, the code is for the old warcrys still, but it should still work fine regarding keep rage up. I would suggest you set proper cooldown using ctrl+click and see if that fixes the issue. i also pushed some code change with which should not affect the issue though.
