### ISSUE TITLE
Autoattack doesn't work. Flicker strike works though but Cyclone doesn't.

### ISSUE THREAD

**Issue by cectertran** [totalschaden/copilot#6]

**Comment by totalschaden** [comment]
Im using Cyclone myself, works fantastic. Make sure you have it on a Key, thats before a Mouse Key, if you have it on Mouse too. Or dont set it to any Mouse Key.

**Comment by cectertran** [comment]
I dunno man it stucks for some reason. Only works when it wants to.

**Comment by totalschaden** [comment]
So you made sure a Key Bound Cyclone is before Mouse Cyclone ? Have a Screenshot of you Skillbar ?

**Comment by cectertran** [comment]
https://imgur.com/RBlvVHc

**Comment by totalschaden** [comment]
Should work fine. Is you Mana showing more then the cost on the Skill ? It wont work with the mana from ES node.

**Comment by cectertran** [comment]
Ya i dunno man. Was working fine till I have my Vortex ready and Vaal ice nova. Im on life nodes.

**Comment by totalschaden** [comment]
It could be a problem with Ice Nova as its rated for Auto Attack too, try to remove it from the bar.

**Comment by cectertran** [comment]
Yea same thing. It stucks then attack when it once too but now its more often than before.

**Comment by totalschaden** [comment]
Your running any non instant cast that could interrupt it ? maybe try to remove everything from the bars and see if it works fine then. Also make sure if you change around gems/skillbar to make a mapchange, so it would update the changes.

**Comment by cectertran** [comment]
Fixed it. Just downloaded tehcheat's fork and it works fine.

**Comment by totalschaden** [comment]
Oh, where you using the other fork from queuete  ?

**Comment by cectertran** [comment]
Yea man. It stuck again lol. Using queutee again.

**Comment by totalschaden** [comment]
Dunno im using Tehcheats fork no Problem there, if it was working for you there too I would recommend you get it again. Not going to debug for a fork im not using.
